version: '3'

services:
  tyk:
    image: tykio/tyk-gateway
    ports:
      - 8080:8080
    volumes:
      - ./tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
    environment:
      - TYK_GW_SECRET=key12345
    depends_on:
      - actor
      - movie
      - redis

  redis:
    image: redis:latest

  actor:
    build: ./Actor
    expose:
      - 3000

  movie:
    build: ./Movie
    expose:
      - 3000
