version: '3'

services:
  api-gateway:
    image: express-gateway
    container_name: express-gateway
    volumes:
      - ./Config:/var/lib/eg
    ports:
      - "8080:8080"
      - "9876:9876"

  actor:
    build: ./Actor
    container_name: actor
    expose:
      - 3000

  movie:
    build: ./Movie
    container_name: movie
    expose:
      - 8000
