http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  actors:
    host: localhost
    paths: ["/actors", "/actors/*"]
  movies:
    host: localhost
    paths: ["/movies", "/movies/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  actorService:
    url: "http://actor:3000"
  movieService:
    url: "http://movie:3000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  actorPipeline:
    apiEndpoints:
      - actors
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: actorService
              changeOrigin: true
  moviePipeline:
    apiEndpoints:
      - movies
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: movieService
              changeOrigin: true
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
